# Generated by Django 3.2 on 2021-04-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='users',
            new_name='user',
        ),
    ]
